### ISSUE TITLE
Email domain validation

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-nuxt3#29]
We have quite a lot of problems with people putting in invalid email addresses due to typos.  We have some code in `EmailValidator` that queries the server to spot typos, but this only works for typos in popular domains.

It looks like Google has an API which we could use to check whether a domain name is resolvable to MX records or a hostname:

https://developers.google.com/speed/public-dns/docs/doh

Can you try using this from `EmailValidator` too?  Async, not blocking.

**Comment by edwh** [comment]
@misterpekert I put this PR live, but I don't think it works.  For example on the `/forgot` page, or when posting, it never emits `valid`.  I've reverted it from production - please take another look.

**Comment by misterpekert** [comment]
@edwh, there was a small typo fixed here (#49). I think it might be why it never emitted `valid`. I'll prepare a pull request bringing back reverted changes, and we can have a call to see what exactly doesn't work as expected.

**Comment by edwh** [comment]
@misterpekert I tested this a bit and hit a couple of problems.

If I go to `http://localhost:3002/give/whoami` then I see this exception:

![image](https://github.com/Freegle/iznik-nuxt3/assets/56696/e733b5f0-6b6d-49ff-9772-e5c811774e63)

If I put in an email of `edward@ehibbertzzz.org.uk` then 
* I correctly see the error.  
* If I then click into the email box and delete the `zzz` I still see the error.
* The new lookup doesn't seem to be triggered until I click out of the email box - but users won't do that.
